### ISSUE TITLE
Alert close button align issues

### ISSUE THREAD

**Issue by rodrigorhas** [DesignRevision/shards-vue#3]
## Expected Behavior

To be aligned as expected
## Current Behavior

Align issues

## Steps to Reproduce
1. Access https://designrevision.com/docs/shards-vue/components/alert
2. At the dismissables
3. Check the close button

## Possible Solution

```css
// fix
.alert-dismissible .close {
    top: 0;
    right: 0;
    padding: .75rem 1.25rem 1.25rem;
    transition: all .25s cubic-bezier(.27,.01,.38,1.06);
    line-height: 1.2rem;
}

// Previous
.alert-dismissible .close {
    top: 0;
    right: 0;
    padding: .75rem 1.25rem;
    transition: all .25s cubic-bezier(.27,.01,.38,1.06);
}
```
